head:
  quad1:
    analog_inputs:
      low: 1
      high: 9
    channel: 1
  quad2:
    analog_inputs:
      low: 2
      high: 10
    channel: 2
  quad3:
    analog_inputs:
      low: 3
      high: 11
    channel: 3
  quad4:
    analog_inputs:
      low: 4
      high: 12
    channel: 4
  quad5:
    analog_inputs:
      low: 5
      high: 13
    channel: 5
  quad6:
    analog_inputs:
      low: 6
      high: 14
    channel: 6
  system:
    channel: 7
fill_duration_full: 20
dispense_duration_full: 10
pre_cylinder_fill_duration: 2
post_cylinder_fill_duration: 4
volume_crossover: 6
volume_max: 10
volume_threshold_initial: 1.0
fill_duration_all_cylinders: 250
fill_duration_one_cylinder: 100
balance_zero_duration: 4
adc_sample_count: 11
fill_duration_inc: 500
fill_duration_max: 12000
run_count: 5
weight_sample_count: 11
dispense_goals:
  - 5
  - 4
  - 3
  - 2
  - 1
